name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build for multiple platforms
      run: |
        # Build for Linux amd64
        GOOS=linux GOARCH=amd64 go build -o vs-linux-amd64 vs.go
        
        # Build for Linux arm64
        GOOS=linux GOARCH=arm64 go build -o vs-linux-arm64 vs.go
        
        # Build for Windows amd64
        GOOS=windows GOARCH=amd64 go build -o vs-windows-amd64.exe vs.go
        
        # Build for macOS amd64
        GOOS=darwin GOARCH=amd64 go build -o vs-darwin-amd64 vs.go
        
        # Build for macOS arm64
        GOOS=darwin GOARCH=arm64 go build -o vs-darwin-arm64 vs.go
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: vs-binaries
        path: |
          vs-linux-amd64
          vs-linux-arm64
          vs-windows-amd64.exe
          vs-darwin-amd64
          vs-darwin-arm64
