name: Build

on:
  push:
    branches: [ master ]
    paths:
      - '**.go'

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - goos: linux
            goarch: amd64
            binary: vs-linux-amd64
          - goos: linux
            goarch: arm64
            binary: vs-linux-arm64
          - goos: windows
            goarch: amd64
            binary: vs-windows-amd64.exe
          - goos: darwin
            goarch: amd64
            binary: vs-darwin-amd64
          - goos: darwin
            goarch: arm64
            binary: vs-darwin-arm64
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Build for ${{ matrix.goos }} ${{ matrix.goarch }}
      run: GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ${{ matrix.binary }} vs.go
    
    - name: Upload ${{ matrix.goos }} ${{ matrix.goarch }} artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.binary }}
        path: ${{ matrix.binary }}
