name: Validate

on:
  pull_request:
    branches: [ master ]
    types: [opened, reopened, synchronize]
    paths:
      - '**.go'

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        go-version: [ '1.18', '1.19', '1.20', '1.21' ]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    - name: Verify dependencies
      run: go mod verify
    
    - name: Build
      run: go build -v ./...
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Run tests with race detection
      run: go test -race -v ./...
    
    - name: Run tests with coverage
      run: go test -cover -v ./...
    
    - name: Run benchmarks
      run: go test -bench=. -v ./...
    
    - name: Run go vet
      run: go vet ./...
    
    - name: Check code formatting
      run: |
        unformatted=$(gofmt -l .)
        if [ -n "$unformatted" ]; then
          echo "The following files need formatting:"
          echo "$unformatted"
          exit 1
        fi
